### ISSUE TITLE
Fix state pension label positioning and behavior

### ISSUE THREAD

**Issue by DannyW86** [GroupDigitalHub/il-cb-project#62]
State pension toggle label is not sitting right, switch should say ‘ON’ in its current default position (when the background is green). 

![image](https://user-images.githubusercontent.com/1696371/78024691-b6392e00-7350-11ea-9e3f-c5857ae84181.png)

**Comment by conye9980** [comment]
@DannyW86 Made changes now for review, thanks!

**Comment by DannyW86** [comment]
This has been updated by Conor and is now displaying and behaving properly on my 13" screen 

<img width="537" alt="Screenshot 2020-04-01 at 11 41 03" src="https://user-images.githubusercontent.com/1696371/78130185-b862c180-7410-11ea-9c36-32b6d69b4121.png">

**Comment by DannyW86** [comment]
Issue can be closed
