### ISSUE TITLE
Dashboard (mobile) - Profile Icon icon

### ISSUE THREAD

**Issue by DannyW86** [GroupDigitalHub/il-cb-project#65]
Can we change the profile icon on the right so it’s just the blue icon without the oval button? The icon is not sitting right in the oval. If the icon was made to be a slightly larger on its own it would look cleaner.

![image](https://user-images.githubusercontent.com/1696371/78025686-5b083b00-7352-11ea-9222-d36a37496ef8.png)

**Comment by conye9980** [comment]
Change made
